### ISSUE TITLE
Calls to FreeType to rasterize glyphs crash

### ISSUE THREAD

**Issue by AdrianGjonca** [rhaleblian/dslibris#68]
<img width="663" height="998" alt="Image" src="https://github.com/user-attachments/assets/230e8290-4ce9-4419-8648-c82fffd00bd5" />

<img width="966" height="1077" alt="Image" src="https://github.com/user-attachments/assets/4896b3ec-ba0a-42af-98f9-635e538a9f40" />

Hello,
I'm trying to compile and run dslibris from source (so I can attempt to experiment with the source). When I run the official release version (whether on DS or actual hardware) it works just fine. However, when I attempt to compile the source and run the resulting executable, it produces a blank bottom screen on both the original hardware, and on the emulator.

This is the last section of console output from melonDS (my choice of emulator):
remapping DTCM 3000000 3004000 0 fffff000
Game is now booting
Opened "/home/adrian/.config/melonDS/melonDS.toml" with FileMode 0x1 (effective mode "rb")
Opened "/home/adrian/.config/melonDS/melonDS.toml" with FileMode 0x20 (effective mode "ab")
remapping DTCM ffffffff ffffffff 3000000 2ffc000
remapping DTCM 2ff0000 2ff4000 ffffffff ffffffff
PU: region 0 = 04000033 : enabled, start: 04000000 size: 19
PU: region 1 = 0200002B : enabled, start: 02000000 size: 15
PU: region 2 = 00000000 : disabled, start: 00000000 size: 00
Failed to open "./dslibris.ml1" with FileMode 0x1 (effective mode "rb")
Failed to open "./dslibris.ml2" with FileMode 0x1 (effective mode "rb")
Failed to open "./dslibris.ml3" with FileMode 0x1 (effective mode "rb")
Failed to open "./dslibris.ml4" with FileMode 0x1 (effective mode "rb")
Failed to open "./dslibris.ml5" with FileMode 0x1 (effective mode "rb")
Failed to open "./dslibris.ml6" with FileMode 0x1 (effective mode "rb")
Failed to open "./dslibris.ml7" with FileMode 0x1 (effective mode "rb")
Failed to open "./dslibris.ml8" with FileMode 0x1 (effective mode "rb")
PU: region 3 = 00000000 : disabled, start: 00000000 size: 00
PU: region 4 = 02FF001F : enabled, start: 02FF0000 size: 0F
PU: region 5 = 01FF801D : enabled, start: 01FF8000 size: 0E
PU: region 6 = FFFF001D : enabled, start: FFFF0000 size: 0E
PU: region 7 = 00000017 : enabled, start: 00000000 size: 0B
PU region 0: 04000000-07FFFFFF, user=03 priv=03, 06330033/66600060
PU region 1: 02000000-023FFFFF, user=77 priv=77, 06330033/66600060
PU region 4: 02FF0000-02FFFFFF, user=03 priv=03, 06330033/66600060
PU region 5: 01FF8000-01FFFFFF, user=07 priv=07, 06330033/66600060
PU region 6: FFFF0000-FFFF7FFF, user=55 priv=55, 06330033/66600060
PU region 7: 00000000-00000FFF, user=04 priv=04, 06330033/66600060
unknown ARM9 IO write32 04001060 00000000 020B9BF4
unknown ARM9 IO write32 04001064 00000000 020B9BF4
unknown ARM9 IO write32 04001068 00000000 020B9BF4
ARM9: data abort (02062DCC)

And this is the screen output:
image.png
The screen output looks identical on running my own build on my DSLite.

If you know what I could potentially be doing wrong it would be of great help.

Kind Regards,
Adrian Gjonca

**Comment by AdrianGjonca** [comment]
On further investigation I have found that the program seems to be stuck on an infinite loop on calls to FT_Load_Char.

**Comment by rhaleblian** [comment]
Is melonDS' debugger indicating the infloop?  What melonDS version and platform are you running?  DeSmuME debugging isn't available anymore.

**Comment by rhaleblian** [comment]
> What melonDS version and platform are you running? 

Looks like you're on Linux.

**Comment by AdrianGjonca** [comment]
![Image](https://github.com/user-attachments/assets/816ac2ae-24c9-43d0-8095-9e22f94c27c8)

![Image](https://github.com/user-attachments/assets/acb88c36-00f4-474c-a49a-d9e2692d3154)

**Comment by rhaleblian** [comment]
Feels like (a) a font file is missing (b) it will not open (c) there was new code for FreeType 2.13 that's missing.

**Comment by AdrianGjonca** [comment]
The thing freezes on the console mode if and of the font files are missing as well so  I know it is not (a) and believe it is not (b) as console output shows them loading.

**Comment by rhaleblian** [comment]
> No matter how many books I do it doesn't work but there are 7 books in my /Book/ directory.

Yeah that's no problem.

> Does it work for you with a binary compiled freshly with FreeType 2.13?

As above, very much no, and the reasons pile up.  "it" is `main` branch HEAD.
I'll be pushing to `libnds2` with fixes as we go... watch it

**Comment by rhaleblian** [comment]
Tore out the key code into a small example, crashes whenever we want a bitmap made from an outline glyph.

**Comment by rhaleblian** [comment]
<img width="1512" height="982" alt="Image" src="https://github.com/user-attachments/assets/d2119136-a5ec-4e66-9e22-7c3b4c646ae6" />
Using a font with a bitmap strike added, the console shows a bitmap (letter 'F').

**Comment by rhaleblian** [comment]
For various calls that pass FT_OPEN_RENDER, or a direct render call, Guru is here
``` 0x02062bac: gray_convert_glyph at smooth.c:? ```

**Comment by AdrianGjonca** [comment]
Might an easier solution be to use a legacy version of FreeType?

**Comment by rhaleblian** [comment]
Maybe, if we can find out what that version was.  2.10.1 doesn't seem better.
We would need to build that ourselves and skip the dkp-pacman version.

**Comment by AdrianGjonca** [comment]
I tried building version 2.6 (or something) but was struggling. You might have better experience then me in this domain if you can give it a go. Do you remember when you compiled release version 1.5.2? Could maybe go off that. I think 2.9 didnt work for me neither

**Comment by rhaleblian** [comment]
Actually i want to send you a script that makes building any given  FreeType version easier.  Stand by.

**Comment by AdrianGjonca** [comment]
Unless you hadn't updated your packages since 2023

**Comment by rhaleblian** [comment]
Check out branch `dev` and try

    ./scripts/install-freetype 2.10.1

The build should fall into `portlibs/`.

**Comment by rhaleblian** [comment]
We should go waay back, to the first version devkitPro ever released.

**Comment by AdrianGjonca** [comment]
What's the plan now. Figure out a way to build with old versions of the libraries or attempt to figure out what's going on with the current versions?

Im struggling to build an equivalent script for zlib at this point

**Comment by rhaleblian** [comment]
No worries, thanks for putting in effort.  Sorry if I'm abrupt, there's no intent to be derogatory, I'm tired and lack time.
The ppl who use dslibris will be appreciative that you help keep it viable.

1. attempt a build with the oldest FreeType we could have had

The code used to have build scripts for all of the devs, it took time to make working ones.  Going back in commits to when a "portlibs/" directory existed should reveal them.  Failing that, the PKGBUILD files in `devkitPro/pacman` are also source for setting up a build.

2. if no help, think more about the problem with the current version.

I pushed a script to get the source line for the address where we crash, e.g.

ray@cobalt:~/Developer/dslibris$ ./scripts/addr2line 0x020099ca
0x020099ca: Text::GetGlyph(unsigned long, int, FT_FaceRec_*) at ??:?

<img width="1512" height="982" alt="Image" src="https://github.com/user-attachments/assets/670200e9-94db-419d-a90c-f5df29b2fd22" />

We could possibly get this to report the deeper problem by building FreeType with enough symbol info to got deeper and tell us where in _FreeType_ we crash.

**Comment by AdrianGjonca** [comment]
What is this 'Guru Meditation Error'. I'm assuming it is a debugging tool based on the crashes on the Amiga.
But are you invoking it yourself or is it just crashing and then showing me this.

I have successfully compiled freetype-2.4.8 but I still get the guru meditation error

**Comment by AdrianGjonca** [comment]
There are some modifications you have to make to a devkitpro header for things to work however. I'm gonna work on a fix for that on my fork in a second

**Comment by rhaleblian** [comment]
> What is this 'Guru Meditation Error'
Provided by devkitPro when you call `defaultExceptionHandler()`

**Comment by rhaleblian** [comment]
With my own dep builds I got back to some workable state.

<img width="276" height="458" alt="Image" src="https://github.com/user-attachments/assets/c2499d28-b156-4a01-9900-4e26ff37de05" />

Details about this are in PR comments.

**Comment by rhaleblian** [comment]
Fine.

**Comment by rhaleblian** [comment]
#76 merged to `main`
